
    - name: Determine if laptop
      command: laptop-detect
      register: is_laptop
      ignore_errors: yes
      tags:
      - monitoring
      - run

    - name: Install htop for process monitoring
      apt: pkg=htop
      become: yes
      tags:
      - monitoring
      - run

    - name: Install smem for memory monitoring
      apt: pkg=smem
      become: yes
      tags:
      - monitoring
      - run

    - name: Install iftop for network monitoring
      apt: pkg=iftop
      become: yes
      tags:
      - monitoring
      - run

    - name: Install iotop for disk I/O monitoring
      apt: pkg=iotop
      become: yes
      tags:
      - monitoring
      - run

    - name: Install PowerTOP to track power consumption
      apt: pkg=powertop
      when: is_laptop|succeeded
      become: yes
      tags:
      - monitoring
      - run

    - name: Install Phoronix Test Suite benchmarking platform
      apt: pkg=phoronix-test-suite
      become: yes
      tags:
      - monitoring
      - run

    - name: Install PCP GUI
      apt: pkg=pcp-gui
      become: yes
      tags:
      - monitoring
      - run

    - name: Install Wireshark
      apt: pkg=wireshark
      become: yes
      tags:
      - monitoring
      - run

    - name: Install whois
      apt: pkg=whois
      become: yes
      tags:
      - monitoring
      - run

    - name: Install HTTPie cURL wrapper
      apt: pkg=httpie
      become: yes
      tags:
      - monitoring
      - run

    - name: Install lynx command line browser
      apt: pkg=lynx
      become: yes
      tags:
      - monitoring
      - run

    - name: Install gparted partition editor
      apt: pkg={{ item }}
      with_items:
      - gpart
      - gparted
      become: yes
      tags:
      - monitoring
      - run

    - name: Install smartmontools applications for testing hard drives
      apt: pkg=smartmontools
      become: yes
      tags:
      - monitoring
      - run

    - name: Install TestDisk partition scanner and disk recovery tool
      apt: pkg=testdisk
      become: yes
      tags:
      - monitoring
      - run

    - name: Install NCurses Disk Usage utility
      apt: pkg=ncdu
      become: yes
      tags:
      - monitoring
      - run

    - name: Install wondershaper for limiting adapter bandwidth
      apt: pkg=wondershaper
      become: yes
      tags:
      - monitoring
      - run
