
    - name: Determine if laptop
      command: laptop-detect
      register: is_laptop
      ignore_errors: yes
      tags:
      - monitoring
      - run

    - name: Install tor anonymizing overlay network for TCP
      apt: pkg=tor
      tags:
      - monitoring
      - run
      become: yes

    - name: Disable tor startup
      shell: update-rc.d tor disable
      tags:
      - monitoring
      - run
      become: yes

    - name: Add Penetration Testing Tools apt repository
      apt_repository: repo="ppa:3lack7ragon/blackdragon-penetration-testing-ppa" update_cache=yes
      become: yes
      tags:
      - monitoring
      - run

    - name: Install rainbowcrack
      apt: pkg=rainbowcrack
      become: yes
      tags:
      - monitoring
      - run

    - name: Install ncrack network authentication cracking tool
      apt: pkg=ncrack
      become: yes
      tags:
      - monitoring
      - run

    - name: Install skipfish web application security reconnaissance tool
      apt: pkg=skipfish
      become: yes
      tags:
      - monitoring
      - run

    - name: Install Nmap for network discovery and security auditing
      apt: pkg=nmap
      become: yes
      tags:
      - monitoring
      - run

    - name: Install dnsmap for brute force DNS name discovery
      apt: pkg=dnsmap
      become: yes
      tags:
      - monitoring
      - run

    - name: Install htop for process monitoring
      apt: pkg=htop
      become: yes
      tags:
      - monitoring
      - run

    - name: Install smem for memory monitoring
      apt: pkg=smem
      become: yes
      tags:
      - monitoring
      - run

    - name: Install iftop for network monitoring
      apt: pkg=iftop
      become: yes
      tags:
      - monitoring
      - run

    - name: Install iotop for disk I/O monitoring
      apt: pkg=iotop
      become: yes
      tags:
      - monitoring
      - run

    - name: Install PowerTOP to track power consumption
      apt: pkg=powertop
      when: is_laptop|succeeded
      become: yes
      tags:
      - monitoring
      - run

    - name: Install Phoronix Test Suite benchmarking platform
      apt: pkg=phoronix-test-suite
      become: yes
      tags:
      - monitoring
      - run

    - name: Install PCP GUI
      apt: pkg=pcp-gui
      become: yes
      tags:
      - monitoring
      - run

    - name: Install Wireshark
      apt: pkg=wireshark
      become: yes
      tags:
      - monitoring
      - run

    - name: Install hwinfo
      apt: pkg=hwinfo
      become: yes
      tags:
      - monitoring
      - run

    - name: Install whois
      apt: pkg=whois
      become: yes
      tags:
      - monitoring
      - run

    - name: Install HTTPie cURL wrapper
      apt: pkg=httpie
      become: yes
      tags:
      - monitoring
      - run

    - name: Install lynx command line browser
      apt: pkg=lynx
      become: yes
      tags:
      - monitoring
      - run

    - name: Install gparted partition editor
      apt: pkg={{ item }}
      with_items:
      - gpart
      - gparted
      become: yes
      tags:
      - monitoring
      - run

    - name: Install TestDisk partition scanner and disk recovery tool
      apt: pkg=testdisk
      become: yes
      tags:
      - monitoring
      - run

    - name: Install wondershaper for limiting adapter bandwidth
      apt: pkg=wondershaper
      become: yes
      tags:
      - monitoring
      - run
