
    - name: Install PCP GUI
      apt: pkg=pcp-gui
      become: yes

    - name: Install Nmap for network discovery and security auditing
      apt: pkg=nmap
      become: yes
  
    - name: Determine if laptop
      command: laptop-detect
      register: is_laptop
      ignore_errors: yes

    - name: Install PowerTOP to track power consumption
      apt: pkg=powertop
      when: is_laptop|succeeded
      become: yes
