
    - name: Determine if laptop
      command: laptop-detect
      register: is_laptop
      ignore_errors: yes
      tags:
      - monitoring
      - run

    - name: Install Nmap for network discovery and security auditing
      apt: pkg=nmap
      become: yes
      tags:
      - monitoring
      - run

    - name: Install ncrack network authentication cracking tool
      apt: pkg=ncrack
      become: yes
      tags:
      - monitoring
      - run

    - name: Install htop for process monitoring
      apt: pkg=htop
      become: yes
      tags:
      - monitoring
      - run

    - name: Install smem for memory monitoring
      apt: pkg=smem
      become: yes
      tags:
      - monitoring
      - run

    - name: Install iftop for network monitoring
      apt: pkg=iftop
      become: yes
      tags:
      - monitoring
      - run

    - name: Install iotop for disk I/O monitoring
      apt: pkg=iotop
      become: yes
      tags:
      - monitoring
      - run

    - name: Install PowerTOP to track power consumption
      apt: pkg=powertop
      when: is_laptop|succeeded
      become: yes
      tags:
      - monitoring
      - run

    - name: Install Phoronix Test Suite benchmarking platform
      apt: pkg=phoronix-test-suite
      become: yes
      tags:
      - monitoring
      - run

    - name: Install PCP GUI
      apt: pkg=pcp-gui
      become: yes
      tags:
      - monitoring
      - run

    - name: Install Wireshark
      apt: pkg=wireshark
      become: yes
      tags:
      - monitoring
      - run

    - name: Install hwinfo
      apt: pkg=hwinfo
      become: yes
      tags:
      - monitoring
      - run

    - name: Install whois
      apt: pkg=whois
      become: yes
      tags:
      - monitoring
      - run

    - name: Add Penetration Testing Tools apt repository
      apt_repository: repo="ppa:3lack7ragon/blackdragon-penetration-testing-ppa" update_cache=yes
      become: yes
      tags:
      - monitoring
      - run

    - name: Install rainbowcrack
      apt: pkg=rainbowcrack
      become: yes
      tags:
      - monitoring
      - run
